version: 2.0

defaults: &defaults
  working_directory: /workspace/search-content-generator
  docker:
    - image: circleci/node:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - run: 
          name: Run tests
          command: npm test

      - persist_to_workspace:
          root: /workspace
          paths:
            - search-content-generator

  deploy-staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy staging application 
          command: |
            env AWS_BUCKET_SUFFIX="$AWS_BUCKET_SUFFIX" \
            env AWS_DEFAULT_ROLE_ARN="$STAGING_AWS_DEFAULT_ROLE_ARN" \
            env AWS_ACCESS_KEY_ID="$STAGING_AWS_ACCESS_KEY_ID" \
            env AWS_SECRET_ACCESS_KEY="$STAGING_AWS_SECRET_ACCESS_KEY" \
            serverless deploy --stage staging

  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy production application 
          command: |
            env AWS_BUCKET_SUFFIX="$AWS_BUCKET_SUFFIX" \
            env AWS_DEFAULT_ROLE_ARN="$PRODUCTION_AWS_DEFAULT_ROLE_ARN" \
            env AWS_ACCESS_KEY_ID="$PRODUCTION_AWS_ACCESS_KEY_ID" \
            env AWS_SECRET_ACCESS_KEY="$PRODUCTION_AWS_SECRET_ACCESS_KEY" \
            serverless deploy --stage production

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
                only: /^v.*/
            branches:
                only: init-configuration
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
                only: init-configuration
      - approve-deploy-production:
          type: approval
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy-production:
          requires:
            - approve-deploy-production
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/